baseURL = "https://www.sgarcia.dev/"
languageCode = "en-us"
theme = "owntheme"

#Page Title (tab title)
title = "Sergi García Ibáñez"
sectionPagesMenu = "menu"


[ params ]
[ params.social ]
    email = "me@sgarcia.dev"
    github = "Sergi030"
    gitlab = "Mehcachis"
    linkedin = "sergi-garcia-ibanez"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = -100

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = -90

  [[menu.main]]
    name = "About/Contact"
    url = "/about/"
    weight = -80
