baseURL = "www.sgarcia.dev"
languageCode = "en-us"
theme = "owntheme"

#Page Title (tab title)
title = "Sergi García Ibáñez"

sectionPagesMenu = "menu"


[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = -100

  [[menu.main]]
    name = "Posts"
    url = "/posts"
    weight = -90

  [[menu.main]]
    name = "About/Contact"
    url = "/about"
    weight = -80
