name: Hugo deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
    
    
      - name: Add SSH Key
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          echo $DEPLOY_KEY | base64 -d > ~/id_rsa && chmod 600 ~/id_rsa
              
      - name: Checkout submodules
        run: |
          eval `ssh-agent -s` && ssh-add ~/id_rsa && git submodule update --init --recursive && git submodule foreach "git checkout master && git pull"
 
      - name: Building Site
        uses: klakegg/actions-hugo@1.0.0      
      
      - name: Deploy Site
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          eval `ssh-agent -s` && ssh-add ~/id_rsa  && git config --global user.email "deploy@sgarcia.dev" && git config --global user.name "Github deployer by Sergi García Ibáñez" && bash ./deploy.sh nobuild   

